//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace Members.DataSources.TeachersUnion
{

    public partial class CDSyndicate : XPLiteObject
    {
        int fSyndicateId;
        [Key]
        [DisplayName(@"ﬂÊœ «·‰ﬁ«»…")]
        public int SyndicateId
        {
            get { return fSyndicateId; }
            set { SetPropertyValue<int>("SyndicateId", ref fSyndicateId, value); }
        }
        string fSyndicate;
        [Size(50)]
        [DisplayName(@"«”„ «·‰ﬁ«»…")]
        public string Syndicate
        {
            get { return fSyndicate; }
            set { SetPropertyValue<string>("Syndicate", ref fSyndicate, value); }
        }
        [Association(@"CDSubCommitteReferencesCDSyndicate", typeof(CDSubCommitte))]
        public XPCollection<CDSubCommitte> CDSubCommittes { get { return GetCollection<CDSubCommitte>("CDSubCommittes"); } }
        [Association(@"TBLMembersReferencesCDSyndicate", typeof(TBLMembers))]
        public XPCollection<TBLMembers> TBLMembersCollection { get { return GetCollection<TBLMembers>("TBLMembersCollection"); } }
    }

}
