//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace Members.DataSources.TeachersUnion
{

    public partial class TBLPrintCard : XPBaseObject
    {
        TBLMembers fMemberId;
        [Key]
        [DisplayName(@"ﬂÊœ «·⁄÷Ê")]
        [Association(@"TBLPrintCardReferencesTBLMembers")]
        public TBLMembers MemberId
        {
            get { return fMemberId; }
            set { SetPropertyValue<TBLMembers>("MemberId", ref fMemberId, value); }
        }
        int fesalno;
        [DisplayName(@"—ﬁ„ «·«Ì’«·")]
        public int esalno
        {
            get { return fesalno; }
            set { SetPropertyValue<int>("esalno", ref fesalno, value); }
        }
        bool fprinted;
        [DisplayName(@" „ ÿ»«⁄ …")]
        public bool printed
        {
            get { return fprinted; }
            set { SetPropertyValue<bool>("printed", ref fprinted, value); }
        }
        DateTime fprintdate;
        [DisplayName(@" «—ÌŒ «·ÿ»«⁄…")]
        public DateTime printdate
        {
            get { return fprintdate; }
            set { SetPropertyValue<DateTime>("printdate", ref fprintdate, value); }
        }
        Users fuserin;
        [DisplayName(@"ﬂÊœ „œŒ· «·»Ì«‰")]
        [Association(@"TBLPrintCardReferencesUsers")]
        public Users userin
        {
            get { return fuserin; }
            set { SetPropertyValue<Users>("userin", ref fuserin, value); }
        }
    }

}
