//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace Members.DataSources.TeachersUnion
{

    public partial class CDCardtype : XPLiteObject
    {
        byte fCardtypeId;
        [Key]
        public byte CardtypeId
        {
            get { return fCardtypeId; }
            set { SetPropertyValue<byte>("CardtypeId", ref fCardtypeId, value); }
        }
        string fCardtype;
        [Size(50)]
        public string Cardtype
        {
            get { return fCardtype; }
            set { SetPropertyValue<string>("Cardtype", ref fCardtype, value); }
        }
        [Association(@"TBLMembersReferencesCDCardtype", typeof(TBLMembers))]
        public XPCollection<TBLMembers> TBLMembersCollection { get { return GetCollection<TBLMembers>("TBLMembersCollection"); } }
    }

}
