#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Members.DataSources.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TeachersUnion")]
	public partial class dsTeachersUnionViewsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dsTeachersUnionViewsDataContext() : 
				base(global::Members.Properties.Settings.Default.TeachersUnionConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dsTeachersUnionViewsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsTeachersUnionViewsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsTeachersUnionViewsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsTeachersUnionViewsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vTBLPrintCard> vTBLPrintCards
		{
			get
			{
				return this.GetTable<vTBLPrintCard>();
			}
		}
		
		public System.Data.Linq.Table<vTBLMembersPlusTBLMemberHala> vTBLMembersPlusTBLMemberHalas
		{
			get
			{
				return this.GetTable<vTBLMembersPlusTBLMemberHala>();
			}
		}
		
		public System.Data.Linq.Table<vTBLMembersPlusShadetKed> vTBLMembersPlusShadetKeds
		{
			get
			{
				return this.GetTable<vTBLMembersPlusShadetKed>();
			}
		}
		
		public System.Data.Linq.Table<vTBLMembersPlusTblMemberAttach> vTBLMembersPlusTblMemberAttaches
		{
			get
			{
				return this.GetTable<vTBLMembersPlusTblMemberAttach>();
			}
		}
		
		public System.Data.Linq.Table<vTBLMazroofPlusReceiptsQry29> vTBLMazroofPlusReceiptsQry29s
		{
			get
			{
				return this.GetTable<vTBLMazroofPlusReceiptsQry29>();
			}
		}
		
		public System.Data.Linq.Table<vTBLMandoop> vTBLMandoops
		{
			get
			{
				return this.GetTable<vTBLMandoop>();
			}
		}
		
		public System.Data.Linq.Table<vTBLAksatDetaile> vTBLAksatDetailes
		{
			get
			{
				return this.GetTable<vTBLAksatDetaile>();
			}
		}
		
		public System.Data.Linq.Table<vTBLMembersQry05> vTBLMembersQry05s
		{
			get
			{
				return this.GetTable<vTBLMembersQry05>();
			}
		}
		
		public System.Data.Linq.Table<vQry33> vQry33s
		{
			get
			{
				return this.GetTable<vQry33>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTBLPrintCard")]
	public partial class vTBLPrintCard
	{
		
		private int _MemberId;
		
		private System.Nullable<bool> _printed;
		
		private System.Nullable<System.DateTime> _printdate;
		
		private string _MemberName;
		
		private System.Nullable<int> _esalno;
		
		private System.Nullable<int> _SyndicateId;
		
		public vTBLPrintCard()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberId", DbType="Int NOT NULL")]
		public int MemberId
		{
			get
			{
				return this._MemberId;
			}
			set
			{
				if ((this._MemberId != value))
				{
					this._MemberId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_printed", DbType="Bit")]
		public System.Nullable<bool> printed
		{
			get
			{
				return this._printed;
			}
			set
			{
				if ((this._printed != value))
				{
					this._printed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_printdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> printdate
		{
			get
			{
				return this._printdate;
			}
			set
			{
				if ((this._printdate != value))
				{
					this._printdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberName", DbType="NVarChar(75)")]
		public string MemberName
		{
			get
			{
				return this._MemberName;
			}
			set
			{
				if ((this._MemberName != value))
				{
					this._MemberName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esalno", DbType="Int")]
		public System.Nullable<int> esalno
		{
			get
			{
				return this._esalno;
			}
			set
			{
				if ((this._esalno != value))
				{
					this._esalno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyndicateId", DbType="Int")]
		public System.Nullable<int> SyndicateId
		{
			get
			{
				return this._SyndicateId;
			}
			set
			{
				if ((this._SyndicateId != value))
				{
					this._SyndicateId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTBLMembersPlusTBLMemberHala")]
	public partial class vTBLMembersPlusTBLMemberHala
	{
		
		private int _MemberId;
		
		private string _MemberName;
		
		private int _KideNumber;
		
		private System.Nullable<int> _esalno;
		
		private string _Syndicate;
		
		private string _MemberSTypeName;
		
		public vTBLMembersPlusTBLMemberHala()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberId", DbType="Int NOT NULL")]
		public int MemberId
		{
			get
			{
				return this._MemberId;
			}
			set
			{
				if ((this._MemberId != value))
				{
					this._MemberId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberName", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string MemberName
		{
			get
			{
				return this._MemberName;
			}
			set
			{
				if ((this._MemberName != value))
				{
					this._MemberName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KideNumber", DbType="Int NOT NULL")]
		public int KideNumber
		{
			get
			{
				return this._KideNumber;
			}
			set
			{
				if ((this._KideNumber != value))
				{
					this._KideNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esalno", DbType="Int")]
		public System.Nullable<int> esalno
		{
			get
			{
				return this._esalno;
			}
			set
			{
				if ((this._esalno != value))
				{
					this._esalno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Syndicate", DbType="NVarChar(50)")]
		public string Syndicate
		{
			get
			{
				return this._Syndicate;
			}
			set
			{
				if ((this._Syndicate != value))
				{
					this._Syndicate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberSTypeName", DbType="NVarChar(50)")]
		public string MemberSTypeName
		{
			get
			{
				return this._MemberSTypeName;
			}
			set
			{
				if ((this._MemberSTypeName != value))
				{
					this._MemberSTypeName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTBLMembersPlusShadetKed")]
	public partial class vTBLMembersPlusShadetKed
	{
		
		private int _MemberId;
		
		private string _MemberName;
		
		private string _Syndicate;
		
		private string _SubCommitte;
		
		private System.Nullable<int> _esalno;
		
		private int _KideNumber;
		
		private string _Jobtitle;
		
		private System.Nullable<bool> _ShadetKed;
		
		private string _MemberNId;
		
		public vTBLMembersPlusShadetKed()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberId", DbType="Int NOT NULL")]
		public int MemberId
		{
			get
			{
				return this._MemberId;
			}
			set
			{
				if ((this._MemberId != value))
				{
					this._MemberId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberName", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string MemberName
		{
			get
			{
				return this._MemberName;
			}
			set
			{
				if ((this._MemberName != value))
				{
					this._MemberName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Syndicate", DbType="NVarChar(50)")]
		public string Syndicate
		{
			get
			{
				return this._Syndicate;
			}
			set
			{
				if ((this._Syndicate != value))
				{
					this._Syndicate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCommitte", DbType="NVarChar(50)")]
		public string SubCommitte
		{
			get
			{
				return this._SubCommitte;
			}
			set
			{
				if ((this._SubCommitte != value))
				{
					this._SubCommitte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esalno", DbType="Int")]
		public System.Nullable<int> esalno
		{
			get
			{
				return this._esalno;
			}
			set
			{
				if ((this._esalno != value))
				{
					this._esalno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KideNumber", DbType="Int NOT NULL")]
		public int KideNumber
		{
			get
			{
				return this._KideNumber;
			}
			set
			{
				if ((this._KideNumber != value))
				{
					this._KideNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jobtitle", DbType="NVarChar(50)")]
		public string Jobtitle
		{
			get
			{
				return this._Jobtitle;
			}
			set
			{
				if ((this._Jobtitle != value))
				{
					this._Jobtitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShadetKed", DbType="Bit")]
		public System.Nullable<bool> ShadetKed
		{
			get
			{
				return this._ShadetKed;
			}
			set
			{
				if ((this._ShadetKed != value))
				{
					this._ShadetKed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberNId", DbType="NVarChar(14)")]
		public string MemberNId
		{
			get
			{
				return this._MemberNId;
			}
			set
			{
				if ((this._MemberNId != value))
				{
					this._MemberNId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTBLMembersPlusTblMemberAttach")]
	public partial class vTBLMembersPlusTblMemberAttach
	{
		
		private int _MemberId;
		
		private string _MemberName;
		
		private int _KideNumber;
		
		private System.Nullable<int> _esalno;
		
		private string _img;
		
		private string _Syndicate;
		
		private System.Nullable<int> _AttachCount;
		
		public vTBLMembersPlusTblMemberAttach()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberId", DbType="Int NOT NULL")]
		public int MemberId
		{
			get
			{
				return this._MemberId;
			}
			set
			{
				if ((this._MemberId != value))
				{
					this._MemberId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberName", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string MemberName
		{
			get
			{
				return this._MemberName;
			}
			set
			{
				if ((this._MemberName != value))
				{
					this._MemberName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KideNumber", DbType="Int NOT NULL")]
		public int KideNumber
		{
			get
			{
				return this._KideNumber;
			}
			set
			{
				if ((this._KideNumber != value))
				{
					this._KideNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esalno", DbType="Int")]
		public System.Nullable<int> esalno
		{
			get
			{
				return this._esalno;
			}
			set
			{
				if ((this._esalno != value))
				{
					this._esalno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(150)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this._img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Syndicate", DbType="NVarChar(50)")]
		public string Syndicate
		{
			get
			{
				return this._Syndicate;
			}
			set
			{
				if ((this._Syndicate != value))
				{
					this._Syndicate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachCount", DbType="Int")]
		public System.Nullable<int> AttachCount
		{
			get
			{
				return this._AttachCount;
			}
			set
			{
				if ((this._AttachCount != value))
				{
					this._AttachCount = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTBLMazroofPlusReceiptsQry29")]
	public partial class vTBLMazroofPlusReceiptsQry29
	{
		
		private int _ReceiptNo;
		
		private byte _mazroofno;
		
		private byte _WorkTypeId;
		
		private byte _workcount;
		
		private string _workrem;
		
		private int _userwork;
		
		private System.DateTime _datework;
		
		private System.Nullable<System.DateTime> _ReceiptDate;
		
		private System.Nullable<int> _CardsCount;
		
		private string _Syndicate;
		
		private string _Cardtype;
		
		private System.Nullable<double> _ReceiptAmount;
		
		private string _WorkType;
		
		private string _RealName;
		
		public vTBLMazroofPlusReceiptsQry29()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptNo", DbType="Int NOT NULL")]
		public int ReceiptNo
		{
			get
			{
				return this._ReceiptNo;
			}
			set
			{
				if ((this._ReceiptNo != value))
				{
					this._ReceiptNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mazroofno", DbType="TinyInt NOT NULL")]
		public byte mazroofno
		{
			get
			{
				return this._mazroofno;
			}
			set
			{
				if ((this._mazroofno != value))
				{
					this._mazroofno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkTypeId", DbType="TinyInt NOT NULL")]
		public byte WorkTypeId
		{
			get
			{
				return this._WorkTypeId;
			}
			set
			{
				if ((this._WorkTypeId != value))
				{
					this._WorkTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workcount", DbType="TinyInt NOT NULL")]
		public byte workcount
		{
			get
			{
				return this._workcount;
			}
			set
			{
				if ((this._workcount != value))
				{
					this._workcount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workrem", DbType="NVarChar(100)")]
		public string workrem
		{
			get
			{
				return this._workrem;
			}
			set
			{
				if ((this._workrem != value))
				{
					this._workrem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userwork", DbType="Int NOT NULL")]
		public int userwork
		{
			get
			{
				return this._userwork;
			}
			set
			{
				if ((this._userwork != value))
				{
					this._userwork = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datework", DbType="DateTime NOT NULL")]
		public System.DateTime datework
		{
			get
			{
				return this._datework;
			}
			set
			{
				if ((this._datework != value))
				{
					this._datework = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptDate", DbType="Date")]
		public System.Nullable<System.DateTime> ReceiptDate
		{
			get
			{
				return this._ReceiptDate;
			}
			set
			{
				if ((this._ReceiptDate != value))
				{
					this._ReceiptDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardsCount", DbType="Int")]
		public System.Nullable<int> CardsCount
		{
			get
			{
				return this._CardsCount;
			}
			set
			{
				if ((this._CardsCount != value))
				{
					this._CardsCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Syndicate", DbType="NVarChar(50)")]
		public string Syndicate
		{
			get
			{
				return this._Syndicate;
			}
			set
			{
				if ((this._Syndicate != value))
				{
					this._Syndicate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cardtype", DbType="NVarChar(50)")]
		public string Cardtype
		{
			get
			{
				return this._Cardtype;
			}
			set
			{
				if ((this._Cardtype != value))
				{
					this._Cardtype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptAmount", DbType="Float")]
		public System.Nullable<double> ReceiptAmount
		{
			get
			{
				return this._ReceiptAmount;
			}
			set
			{
				if ((this._ReceiptAmount != value))
				{
					this._ReceiptAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkType", DbType="NVarChar(50)")]
		public string WorkType
		{
			get
			{
				return this._WorkType;
			}
			set
			{
				if ((this._WorkType != value))
				{
					this._WorkType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this._RealName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTBLMandoop")]
	public partial class vTBLMandoop
	{
		
		private int _MandoopId;
		
		private string _MandoopName;
		
		private string _MandoopNID;
		
		private string _MandoopJOB;
		
		private string _MandoopMOBIL;
		
		private string _MandoopEMAIL;
		
		private int _SyndicateId;
		
		private System.Nullable<int> _userin;
		
		private System.Nullable<System.DateTime> _datein;
		
		private string _MandoopImg;
		
		private System.Nullable<bool> _active;
		
		private string _Syndicate;
		
		private string _RealName;
		
		public vTBLMandoop()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MandoopId", DbType="Int NOT NULL")]
		public int MandoopId
		{
			get
			{
				return this._MandoopId;
			}
			set
			{
				if ((this._MandoopId != value))
				{
					this._MandoopId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MandoopName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MandoopName
		{
			get
			{
				return this._MandoopName;
			}
			set
			{
				if ((this._MandoopName != value))
				{
					this._MandoopName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MandoopNID", DbType="NVarChar(14)")]
		public string MandoopNID
		{
			get
			{
				return this._MandoopNID;
			}
			set
			{
				if ((this._MandoopNID != value))
				{
					this._MandoopNID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MandoopJOB", DbType="NVarChar(50)")]
		public string MandoopJOB
		{
			get
			{
				return this._MandoopJOB;
			}
			set
			{
				if ((this._MandoopJOB != value))
				{
					this._MandoopJOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MandoopMOBIL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MandoopMOBIL
		{
			get
			{
				return this._MandoopMOBIL;
			}
			set
			{
				if ((this._MandoopMOBIL != value))
				{
					this._MandoopMOBIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MandoopEMAIL", DbType="NVarChar(50)")]
		public string MandoopEMAIL
		{
			get
			{
				return this._MandoopEMAIL;
			}
			set
			{
				if ((this._MandoopEMAIL != value))
				{
					this._MandoopEMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyndicateId", DbType="Int NOT NULL")]
		public int SyndicateId
		{
			get
			{
				return this._SyndicateId;
			}
			set
			{
				if ((this._SyndicateId != value))
				{
					this._SyndicateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userin", DbType="Int")]
		public System.Nullable<int> userin
		{
			get
			{
				return this._userin;
			}
			set
			{
				if ((this._userin != value))
				{
					this._userin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datein", DbType="DateTime")]
		public System.Nullable<System.DateTime> datein
		{
			get
			{
				return this._datein;
			}
			set
			{
				if ((this._datein != value))
				{
					this._datein = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MandoopImg", DbType="NVarChar(150)")]
		public string MandoopImg
		{
			get
			{
				return this._MandoopImg;
			}
			set
			{
				if ((this._MandoopImg != value))
				{
					this._MandoopImg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this._active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Syndicate", DbType="NVarChar(50)")]
		public string Syndicate
		{
			get
			{
				return this._Syndicate;
			}
			set
			{
				if ((this._Syndicate != value))
				{
					this._Syndicate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this._RealName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTBLAksatDetailes")]
	public partial class vTBLAksatDetaile
	{
		
		private int _MemberId;
		
		private System.DateTime _datesadad;
		
		private double _sdadmony;
		
		private System.DateTime _datein;
		
		private int _userin;
		
		private System.Nullable<System.DateTime> _kestenddate;
		
		private System.Nullable<double> _mostahk;
		
		private System.Nullable<double> _madfoaa;
		
		private string _esalno;
		
		private System.Nullable<System.DateTime> _esaldate;
		
		private string _RealName;
		
		private string _Syndicate;
		
		private string _SubCommitte;
		
		private string _MemberName;
		
		private System.Nullable<int> _KideNumber;
		
		private string _Cardtype;
		
		private System.Nullable<bool> _Installment;
		
		private System.Nullable<bool> _fawry;
		
		private System.Nullable<int> _SyndicateId;
		
		private System.Nullable<int> _SubCommitteId;
		
		public vTBLAksatDetaile()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberId", DbType="Int NOT NULL")]
		public int MemberId
		{
			get
			{
				return this._MemberId;
			}
			set
			{
				if ((this._MemberId != value))
				{
					this._MemberId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datesadad", DbType="Date NOT NULL")]
		public System.DateTime datesadad
		{
			get
			{
				return this._datesadad;
			}
			set
			{
				if ((this._datesadad != value))
				{
					this._datesadad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdadmony", DbType="Float NOT NULL")]
		public double sdadmony
		{
			get
			{
				return this._sdadmony;
			}
			set
			{
				if ((this._sdadmony != value))
				{
					this._sdadmony = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datein", DbType="DateTime NOT NULL")]
		public System.DateTime datein
		{
			get
			{
				return this._datein;
			}
			set
			{
				if ((this._datein != value))
				{
					this._datein = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userin", DbType="Int NOT NULL")]
		public int userin
		{
			get
			{
				return this._userin;
			}
			set
			{
				if ((this._userin != value))
				{
					this._userin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kestenddate", DbType="Date")]
		public System.Nullable<System.DateTime> kestenddate
		{
			get
			{
				return this._kestenddate;
			}
			set
			{
				if ((this._kestenddate != value))
				{
					this._kestenddate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mostahk", DbType="Float")]
		public System.Nullable<double> mostahk
		{
			get
			{
				return this._mostahk;
			}
			set
			{
				if ((this._mostahk != value))
				{
					this._mostahk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madfoaa", DbType="Float")]
		public System.Nullable<double> madfoaa
		{
			get
			{
				return this._madfoaa;
			}
			set
			{
				if ((this._madfoaa != value))
				{
					this._madfoaa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esalno", DbType="NVarChar(50)")]
		public string esalno
		{
			get
			{
				return this._esalno;
			}
			set
			{
				if ((this._esalno != value))
				{
					this._esalno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esaldate", DbType="Date")]
		public System.Nullable<System.DateTime> esaldate
		{
			get
			{
				return this._esaldate;
			}
			set
			{
				if ((this._esaldate != value))
				{
					this._esaldate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this._RealName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Syndicate", DbType="NVarChar(50)")]
		public string Syndicate
		{
			get
			{
				return this._Syndicate;
			}
			set
			{
				if ((this._Syndicate != value))
				{
					this._Syndicate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCommitte", DbType="NVarChar(50)")]
		public string SubCommitte
		{
			get
			{
				return this._SubCommitte;
			}
			set
			{
				if ((this._SubCommitte != value))
				{
					this._SubCommitte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberName", DbType="NVarChar(75)")]
		public string MemberName
		{
			get
			{
				return this._MemberName;
			}
			set
			{
				if ((this._MemberName != value))
				{
					this._MemberName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KideNumber", DbType="Int")]
		public System.Nullable<int> KideNumber
		{
			get
			{
				return this._KideNumber;
			}
			set
			{
				if ((this._KideNumber != value))
				{
					this._KideNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cardtype", DbType="NVarChar(50)")]
		public string Cardtype
		{
			get
			{
				return this._Cardtype;
			}
			set
			{
				if ((this._Cardtype != value))
				{
					this._Cardtype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Installment", DbType="Bit")]
		public System.Nullable<bool> Installment
		{
			get
			{
				return this._Installment;
			}
			set
			{
				if ((this._Installment != value))
				{
					this._Installment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fawry", DbType="Bit")]
		public System.Nullable<bool> fawry
		{
			get
			{
				return this._fawry;
			}
			set
			{
				if ((this._fawry != value))
				{
					this._fawry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyndicateId", DbType="Int")]
		public System.Nullable<int> SyndicateId
		{
			get
			{
				return this._SyndicateId;
			}
			set
			{
				if ((this._SyndicateId != value))
				{
					this._SyndicateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCommitteId", DbType="Int")]
		public System.Nullable<int> SubCommitteId
		{
			get
			{
				return this._SubCommitteId;
			}
			set
			{
				if ((this._SubCommitteId != value))
				{
					this._SubCommitteId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTBLMembersQry05")]
	public partial class vTBLMembersQry05
	{
		
		private int _MemberId;
		
		private string _MemberName;
		
		private int _KideNumber;
		
		private System.Nullable<bool> _trheelprog;
		
		private int _SyndicateId;
		
		private System.Nullable<int> _SubCommitteId;
		
		private System.Nullable<int> _MemberShipNumber;
		
		private string _RandomCard;
		
		private string _SubCommitte;
		
		private string _Syndicate;
		
		private System.Nullable<System.DateTime> _datein;
		
		private string _RealName;
		
		private System.Nullable<int> _esalno;
		
		private System.Data.Linq.Binary _Img;
		
		private string _RealNamePrint;
		
		private System.Nullable<bool> _fawry;
		
		private System.Nullable<bool> _printed;
		
		private System.Nullable<System.DateTime> _printdate;
		
		private System.Nullable<bool> _mEdited;
		
		private System.Nullable<int> _userEdit;
		
		private string _EditUserName;
		
		public vTBLMembersQry05()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberId", DbType="Int NOT NULL")]
		public int MemberId
		{
			get
			{
				return this._MemberId;
			}
			set
			{
				if ((this._MemberId != value))
				{
					this._MemberId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberName", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string MemberName
		{
			get
			{
				return this._MemberName;
			}
			set
			{
				if ((this._MemberName != value))
				{
					this._MemberName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KideNumber", DbType="Int NOT NULL")]
		public int KideNumber
		{
			get
			{
				return this._KideNumber;
			}
			set
			{
				if ((this._KideNumber != value))
				{
					this._KideNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trheelprog", DbType="Bit")]
		public System.Nullable<bool> trheelprog
		{
			get
			{
				return this._trheelprog;
			}
			set
			{
				if ((this._trheelprog != value))
				{
					this._trheelprog = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyndicateId", DbType="Int NOT NULL")]
		public int SyndicateId
		{
			get
			{
				return this._SyndicateId;
			}
			set
			{
				if ((this._SyndicateId != value))
				{
					this._SyndicateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCommitteId", DbType="Int")]
		public System.Nullable<int> SubCommitteId
		{
			get
			{
				return this._SubCommitteId;
			}
			set
			{
				if ((this._SubCommitteId != value))
				{
					this._SubCommitteId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberShipNumber", DbType="Int")]
		public System.Nullable<int> MemberShipNumber
		{
			get
			{
				return this._MemberShipNumber;
			}
			set
			{
				if ((this._MemberShipNumber != value))
				{
					this._MemberShipNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RandomCard", DbType="NVarChar(50)")]
		public string RandomCard
		{
			get
			{
				return this._RandomCard;
			}
			set
			{
				if ((this._RandomCard != value))
				{
					this._RandomCard = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCommitte", DbType="NVarChar(50)")]
		public string SubCommitte
		{
			get
			{
				return this._SubCommitte;
			}
			set
			{
				if ((this._SubCommitte != value))
				{
					this._SubCommitte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Syndicate", DbType="NVarChar(50)")]
		public string Syndicate
		{
			get
			{
				return this._Syndicate;
			}
			set
			{
				if ((this._Syndicate != value))
				{
					this._Syndicate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datein", DbType="DateTime")]
		public System.Nullable<System.DateTime> datein
		{
			get
			{
				return this._datein;
			}
			set
			{
				if ((this._datein != value))
				{
					this._datein = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this._RealName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esalno", DbType="Int")]
		public System.Nullable<int> esalno
		{
			get
			{
				return this._esalno;
			}
			set
			{
				if ((this._esalno != value))
				{
					this._esalno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Img", DbType="Binary(30)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Img
		{
			get
			{
				return this._Img;
			}
			set
			{
				if ((this._Img != value))
				{
					this._Img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealNamePrint", DbType="NVarChar(50)")]
		public string RealNamePrint
		{
			get
			{
				return this._RealNamePrint;
			}
			set
			{
				if ((this._RealNamePrint != value))
				{
					this._RealNamePrint = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fawry", DbType="Bit")]
		public System.Nullable<bool> fawry
		{
			get
			{
				return this._fawry;
			}
			set
			{
				if ((this._fawry != value))
				{
					this._fawry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_printed", DbType="Bit")]
		public System.Nullable<bool> printed
		{
			get
			{
				return this._printed;
			}
			set
			{
				if ((this._printed != value))
				{
					this._printed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_printdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> printdate
		{
			get
			{
				return this._printdate;
			}
			set
			{
				if ((this._printdate != value))
				{
					this._printdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mEdited", DbType="Bit")]
		public System.Nullable<bool> mEdited
		{
			get
			{
				return this._mEdited;
			}
			set
			{
				if ((this._mEdited != value))
				{
					this._mEdited = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userEdit", DbType="Int")]
		public System.Nullable<int> userEdit
		{
			get
			{
				return this._userEdit;
			}
			set
			{
				if ((this._userEdit != value))
				{
					this._userEdit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUserName", DbType="NVarChar(50)")]
		public string EditUserName
		{
			get
			{
				return this._EditUserName;
			}
			set
			{
				if ((this._EditUserName != value))
				{
					this._EditUserName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vQry33")]
	public partial class vQry33
	{
		
		private int _ReceiptNo;
		
		private byte _mazroofno;
		
		private byte _WorkTypeId;
		
		private byte _workcount;
		
		private string _workrem;
		
		private int _userwork;
		
		private System.DateTime _datework;
		
		private string _WorkType;
		
		private System.Nullable<System.DateTime> _ReceiptDate;
		
		private string _RealName;
		
		public vQry33()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptNo", DbType="Int NOT NULL")]
		public int ReceiptNo
		{
			get
			{
				return this._ReceiptNo;
			}
			set
			{
				if ((this._ReceiptNo != value))
				{
					this._ReceiptNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mazroofno", DbType="TinyInt NOT NULL")]
		public byte mazroofno
		{
			get
			{
				return this._mazroofno;
			}
			set
			{
				if ((this._mazroofno != value))
				{
					this._mazroofno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkTypeId", DbType="TinyInt NOT NULL")]
		public byte WorkTypeId
		{
			get
			{
				return this._WorkTypeId;
			}
			set
			{
				if ((this._WorkTypeId != value))
				{
					this._WorkTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workcount", DbType="TinyInt NOT NULL")]
		public byte workcount
		{
			get
			{
				return this._workcount;
			}
			set
			{
				if ((this._workcount != value))
				{
					this._workcount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workrem", DbType="NVarChar(100)")]
		public string workrem
		{
			get
			{
				return this._workrem;
			}
			set
			{
				if ((this._workrem != value))
				{
					this._workrem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userwork", DbType="Int NOT NULL")]
		public int userwork
		{
			get
			{
				return this._userwork;
			}
			set
			{
				if ((this._userwork != value))
				{
					this._userwork = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datework", DbType="DateTime NOT NULL")]
		public System.DateTime datework
		{
			get
			{
				return this._datework;
			}
			set
			{
				if ((this._datework != value))
				{
					this._datework = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string WorkType
		{
			get
			{
				return this._WorkType;
			}
			set
			{
				if ((this._WorkType != value))
				{
					this._WorkType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptDate", DbType="Date")]
		public System.Nullable<System.DateTime> ReceiptDate
		{
			get
			{
				return this._ReceiptDate;
			}
			set
			{
				if ((this._ReceiptDate != value))
				{
					this._ReceiptDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this._RealName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
